name: Build Android APK and AAB
on:
  push:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install Dependencies
        run: npm install
      - name: Sync Capacitor
        run: npx cap sync android
        
      - name: Decode Keystore
        run: echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/mi-release-key.jks
        
      - name: Build Debug APK
        working-directory: ./android
        run: ./gradlew assembleDebug
        
      - name: Build Signed AAB
        working-directory: ./android
        run: ./gradlew bundleRelease
        env:
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          STORE_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          
      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          
      - name: Upload Signed AAB
        uses: actions/upload-artifact@v3
        with:
          name: app-release-aab
          path: android/app/build/outputs/bundle/release/app-release.aab
