name: Android Build

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Instalar dependencias y Plugins Nativos
        run: |
          npm install --legacy-peer-deps
          npm install @capacitor/core @capacitor/cli @capacitor/android --legacy-peer-deps
          npm install @capacitor/filesystem @capacitor/share --legacy-peer-deps

      - name: Sincronizar Capacitor
        run: |
          chmod +x node_modules/.bin/cap
          npx cap sync android

      - name: Actualizar SDKs y AGP
        run: |
          sed -i 's/minSdkVersion = .*/minSdkVersion = 23/g' android/variables.gradle
          sed -i 's/compileSdkVersion = .*/compileSdkVersion = 35/g' android/variables.gradle
          sed -i 's/targetSdkVersion = .*/targetSdkVersion = 35/g' android/variables.gradle
          sed -i -E 's/com\.android\.tools\.build:gradle:[0-9\.]+/com.android.tools.build:gradle:8.5.0/g' android/build.gradle

      - name: Actualizar Gradle para soportar Java 21
        run: |
          sed -i 's/distributionUrl=.*/distributionUrl=https\:\/\/services.gradle.org\/distributions\/gradle-8.7-all.zip/g' android/gradle/wrapper/gradle-wrapper.properties

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Generar Keystore y Compilar Android
        env:
          STORE_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          # Decodificar el Keystore
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/mi-release-key.jks
          
          # Compilar APK y AAB
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
          ./gradlew bundleRelease

      - name: Subir APK de prueba
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: android/app/build/outputs/apk/debug/**/*.apk

      - name: Subir AAB para Play Store
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: android/app/build/outputs/bundle/release/**/*.aab