name: Android Build

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Instalar dependencias y Plugins Nativos
        run: |
          npm install --legacy-peer-deps
          npm install @capacitor/core @capacitor/cli @capacitor/android --legacy-peer-deps
          npm install @capacitor/filesystem @capacitor/share --legacy-peer-deps

      - name: Sincronizar Capacitor
        run: |
          chmod +x node_modules/.bin/cap
          npx cap sync android

      - name: Actualizar SDKs y AGP
        run: |
          sed -i 's/minSdkVersion = .*/minSdkVersion = 23/g' android/variables.gradle
          sed -i 's/compileSdkVersion = .*/compileSdkVersion = 36/g' android/variables.gradle
          sed -i 's/targetSdkVersion = .*/targetSdkVersion = 36/g' android/variables.gradle
          sed -i -E 's/com\.android\.tools\.build:gradle:[0-9\.]+/com.android.tools.build:gradle:8.9.1/g' android/build.gradle

      - name: Actualizar Gradle para soportar Java 21 y nuevos plugins
        run: |
          sed -i 's/distributionUrl=.*/distributionUrl=https\:\/\/services.gradle.org\/distributions\/gradle-8.14.3-all.zip/g' android/gradle/wrapper/gradle-wrapper.properties

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Compilar APK de prueba (Debug)
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Subir APK de prueba
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: android/app/build/outputs/apk/debug/**/*.apk